str1="takeuforward"
str2="forward"
res=""
res1=false;
for(i=0;i<str1.length;i++){
    if(str2[0]==str1[i]){
        res=str1.slice(i,i+str2.length)
        console.log(res,i,i+str2.length)
        if(res==str2){
            console.log(i);
            res1=true;
            break;
        }
         }
}
if(!res1){
    console.log("-1");
}